#ifndef HORNET_COMPAT_HH
#define HORNET_COMPAT_HH

#ifdef CONFIG_NEED_MADV_HUGEPAGE
#define MADV_HUGEPAGE MADV_NORMAL
#endif

#ifdef CONFIG_NEED_MAP_ANONYMOUS
#define MAP_ANONYMOUS MAP_ANON
#endif

#endif
